import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png" />
      </Head>
      <main className='bg-very-dark-blue h-screen flex justify-center items-center'>
        <div className='bg-dark-blue aspect-[4/3] mx-8 rounded-2xl p-6 flex flex-col gap-4'>
          <div className='bg-medium-grey rounded-full p-3 w-fit'>
            <img className='w-3.5' src="icon-star.svg" alt="icon star" />
          </div>
          <h1 className='text-white font-overpass-700 text-2xl'>How did we do?</h1>
          <p className='text-light-grey font-overpass-400 text-sm'>Please let us know how we did with your support request. All feedback is appreciated to help us improve our offering!</p>
          <form>
            <fieldset>
              {Array.from(Array(5),(e, i) => {
                return (<>
                    <input className='hidden' type="radio" id={`r${i}`} name='rating' />
                    <label className='' htmlFor={`r${i}`}>{i+1}</label>
                </>)
              })}
            </fieldset>
            <button>SUBMIT</button>
          </form>
        </div>
      </main>
    </>
  )
}
