import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [rating, setRating] = useState(0);
  const [submit, setSubmit] = useState(false);

  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="favicon-32x32.png"
        />
      </Head>
      <main className="flex h-screen items-center justify-center bg-very-dark-blue">
        <div
          className={`mx-8 flex h-96 w-80 justify-center rounded-3xl bg-dark-blue p-6 font-overpass xl:w-96 ${
            submit ? `items-center` : ``
          } flex-col gap-6`}
        >
          {submit ? (
            <>
              <Image
                width="0"
                height="0"
                className="mx-16 w-52"
                src="illustration-thank-you.svg"
                alt="illustration thank you"
              />
              <div className="w-fit rounded-full bg-medium-grey px-3 py-2 text-center text-sm text-orange">
                You selected {rating} out of 5
              </div>
              <div className="flex flex-col items-center">
                <h1 className="text-2xl font-bold text-white">Thank you!</h1>
                <p className="mt-3 text-center text-sm text-light-grey xl:mx-2">
                  We appreciate you taking the time to give a rating. If you
                  ever need more support, don&apos;t hesitate to get in touch!
                </p>
              </div>
            </>
          ) : (
            <>
              <div className="w-fit rounded-full bg-medium-grey p-3">
                <Image
                  width="0"
                  height="0"
                  className="w-3.5"
                  src="icon-star.svg"
                  alt="icon star"
                />
              </div>
              <h1 className="text-2xl font-bold text-white">How did we do?</h1>
              <p className="text-sm text-light-grey">
                Please let us know how we did with your support request. All
                feedback is appreciated to help us improve our offering!
              </p>
              <form>
                <fieldset className="flex justify-between">
                  {Array.from(Array(5), (e, i) => {
                    return (
                      <label htmlFor={`r${i}`} key={i}>
                        <input
                          className="peer hidden"
                          type="radio"
                          id={`r${i}`}
                          name="rating"
                          onClick={() => setRating(i + 1)}
                        />
                        <div className="rounded-full bg-medium-grey py-2 px-4 text-white duration-500 hover:cursor-pointer hover:bg-orange peer-checked:bg-light-grey">
                          {i + 1}
                        </div>
                      </label>
                    );
                  })}
                </fieldset>
                <button
                  onClick={() => setSubmit(true)}
                  className="mt-7 w-full rounded-full bg-orange py-2 text-center text-white duration-500 hover:bg-white hover:text-orange"
                >
                  SUBMIT
                </button>
              </form>
            </>
          )}
        </div>
        <div className="attribution">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            rel="noreferrer"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a href="https://github.com/sanchezmilton">Milton Sánchez</a>.
        </div>
      </main>
    </>
  );
}
