import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [rating, setRating] = useState(0);
  const [submit, setSubmit] = useState(false);

  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png" />
      </Head>
      <main className='bg-very-dark-blue h-screen flex justify-center items-center'>
        <div className={`bg-dark-blue xl:w-96 w-80 font-overpass mx-8 rounded-3xl h-96 p-6 flex justify-center ${submit ? `items-center` : ``} flex-col gap-6`}>
          {submit ?
            <>
              <Image width='0' height='0' className='w-52 mx-16' src="illustration-thank-you.svg" alt="illustration thank you" />
              <div className='text-orange bg-medium-grey text-center w-fit px-3 py-2 rounded-full text-sm'>You selected {rating} out of 5</div>
              <div className='flex flex-col items-center'>
                <h1 className='text-white text-2xl font-bold'>Thank you!</h1>
                <p className='text-light-grey text-sm text-center mt-3 xl:mx-2'>We appreciate you taking the time to give a rating. If you ever need more support, don&apos;t hesitate to get in touch!</p>
              </div>
            </>
            :
            <>
              <div className='bg-medium-grey rounded-full p-3 w-fit'>
                <Image width='0' height='0' className='w-3.5' src="icon-star.svg" alt="icon star" />
              </div>
              <h1 className='text-white text-2xl font-bold'>How did we do?</h1>
              <p className='text-light-grey text-sm'>Please let us know how we did with your support request. All feedback is appreciated to help us improve our offering!</p>
              <form>
                <fieldset className='flex justify-between'>
                  {Array.from(Array(5), (e, i) => {
                    return (<label htmlFor={`r${i}`} key={i}>
                      <input className='hidden peer' type="radio" id={`r${i}`} name='rating' onClick={() => setRating(i + 1)} />
                      <div className='text-white bg-medium-grey rounded-full py-2 px-4 peer-checked:bg-light-grey hover:cursor-pointer hover:bg-orange duration-500'>{i + 1}</div>
                    </label>)
                  })}
                </fieldset>
                <button onClick={() => setSubmit(true)} className='text-white bg-orange rounded-full py-2 w-full text-cente mt-7 hover:bg-white hover:text-orange duration-500'>SUBMIT</button>
              </form>
            </>}
        </div>
        <div className="attribution">
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank" rel='noreferrer'>Frontend Mentor</a>.
          Coded by <a href="https://github.com/sanchezmilton">Milton Sánchez</a>.
        </div>
      </main>
    </>
  )
}
